//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class factores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factores()
        {
            this.valores = new HashSet<valores>();
            this.habilitado = true;
        }
    
        public string nombre { get; set; }
        public bool habilitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<valores> valores { get; set; }

        public string valorBajo
        {
            set
            {

                bool modificado = false;

                foreach (valores v in this.valores)
                    if (v.rating == 0)
                    {
                        modificado = true;
                        v.nombre = value;
                        break;
                    }

                if (!modificado)
                {
                    valores valor = new valores()
                    {
                        nombre = value,
                        rating = 0,
                        nombreFactor = this.nombre
                    };

                    this.valores.Add(valor);
                }
            }

            get
            {

                foreach (valores v in this.valores)
                    if (v.rating == 0)
                        return v.nombre;

                return "";
            }
        }

        public string valorMedio
        {
            set
            {

                bool modificado = false;

                foreach (valores v in this.valores)
                    if (v.rating == 1)
                    {
                        modificado = true;
                        v.nombre = value;
                        break;
                    }

                if (!modificado)
                {
                    valores valor = new valores()
                    {
                        nombre = value,
                        rating = 1,
                        nombreFactor = this.nombre
                    };

                    this.valores.Add(valor);
                }
            }

            get
            {

                foreach (valores v in this.valores)
                    if (v.rating == 1)
                        return v.nombre;

                return "";
            }
        }

        public string valorAlto
        {
            set { 

                bool modificado= false;

                foreach(valores v in this.valores)
                    if (v.rating == 2)
                    {
                        modificado = true;
                        v.nombre = value;
                        break;
                    }

                if (!modificado)
                {
                    valores valor = new valores()
                    {
                        nombre= value,
                        rating= 2,
                        nombreFactor= this.nombre
                    };

                    this.valores.Add(valor);
                }
            }

            get {

                foreach (valores v in this.valores)
                    if (v.rating == 2)
                        return v.nombre;

                return "";
            }
        }

        public override string ToString(){

            string ret = "Clase: factores.\n";
            ret += "Nombre: " + this.nombre + "\n";
            
            foreach(valores v in this.valores)
                ret += "- Valor: " + v.nombre + ". Rating: " + v.rating + "\n";

            return ret;
        }
    }
}
