//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class valores
    {
        public const int RATING_BAJO = 0;
        public const int RATING_MEDIO = 1;
        public const int RATING_ALTO = 2;

        public const int MAXIMO_NOMBRE = 50;

        public string nombre { get; set; }
        public short rating { get; set; }
        public string nombreFactor { get; set; }
    
        public virtual factores factores { get; set; }

        public override string ToString()
        {
            return "Clase 'valores': Nombre= '" + this.nombre + "'. Rating= " + this.rating + ". Factor= '" + this.nombreFactor + "'";
        }
    }
}
