//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class valores
    {
        public static int RATING_BAJO = 0;
        public static int RATING_MEDIO = 1;
        public static int RATING_ALTO = 2;

        public string nombre { get; set; }
        public short rating { get; set; }
        public string nombreFactor { get; set; }
    
        public virtual factores factores { get; set; }
    }
}
