//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Entidades;

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_ProyectoEntities : DbContext
    {
        public DB_ProyectoEntities()
            : base("name=DB_ProyectoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<factores> factores { get; set; }
        public virtual DbSet<valores> valores { get; set; }

        public static void inicializar()
        {
            Database.SetInitializer(new DropCreateDatabaseAlways<DB_ProyectoEntities>());
        }
    }
}
